/**
 * Mild loading indicator for backgrounded async work the player should be
 * aware of (a region/location grid is still being generated by the LLM,
 * the narrator is composing a reply, etc.). Deliberately subtle: a pulsing
 * dot plus a one-word label, no spinner art, no modal — the rest of the
 * UI stays interactive.
 */
type Props = {
  label?: string;
  /** Render inline (vs. as a block). Default true. */
  inline?: boolean;
};

export function LoadingPill({ label = "Generating", inline = true }: Props) {
  const Tag = inline ? "span" : "div";
  return (
    <Tag className="loadingPill" role="status" aria-live="polite">
      <span className="loadingPill__dot" aria-hidden="true" />
      <span className="loadingPill__label">{label}…</span>
    </Tag>
  );
}
